Repository 19dudedemo/hacktober2022, pull requests merged in 2022-10, with the labels that each got.

#2 added lcs.cpp
  lcs.cpp
Labels: hacktoberfest2022

#3 Create stockSpan.cpp
  stockSpan.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#4 Create scrollingBox.css
  scrollingBox.css
Labels: hacktoberfest-accepted

#6 Contributed Login Form of React-Native
  Native_App_front-end/login_form/.expo-shared/assets.json
  Native_App_front-end/login_form/.gitignore
  Native_App_front-end/login_form/App.js
  Native_App_front-end/login_form/app.json
  Native_App_front-end/login_form/assets/adaptive-icon.png
  Native_App_front-end/login_form/assets/agri_logo.png
  Native_App_front-end/login_form/assets/favicon.png
  Native_App_front-end/login_form/assets/icon.png
  Native_App_front-end/login_form/assets/splash.png
  Native_App_front-end/login_form/babel.config.js
  Native_App_front-end/login_form/components/FormButton.js
  Native_App_front-end/login_form/components/FormInput.js
  Native_App_front-end/login_form/components/SocialButton.js
  Native_App_front-end/login_form/navigation/AuthStack.js
  Native_App_front-end/login_form/navigation/Routes.js
  Native_App_front-end/login_form/navigation/index.js
  Native_App_front-end/login_form/package-lock.json
  Native_App_front-end/login_form/package.json
  Native_App_front-end/login_form/screens/LoginScreen.js
  Native_App_front-end/login_form/screens/OnboardingScreen.js
  Native_App_front-end/login_form/screens/SignupScreen.js
  Native_App_front-end/login_form/utils/Dimensions.js
  Readme.md
Labels: hacktoberfest-accepted

#5 Contributed Number of Distinct Islands in Python
  Competitive Programing/Number_of_Distinct_Islands.py
Labels: hacktoberfest-accepted

#7 made changes
  BaseConversionApp/.classpath
  BaseConversionApp/.project
  BaseConversionApp/.settings/org.eclipse.jdt.core.prefs
  BaseConversionApp/bin/loginPackage/LoginToApp.class
  BaseConversionApp/bin/loginPackage/loginClass.class
  BaseConversionApp/bin/mainPackage/MainClass.class
  BaseConversionApp/bin/numDetailsPackage/NumberDetails.class
  BaseConversionApp/bin/numberConvertionPackage/NumberConversion.class
  BaseConversionApp/bin/validationPackage/Validation.class
  BaseConversionApp/src/loginPackage/LoginToApp.java
  BaseConversionApp/src/mainPackage/MainClass.java
  BaseConversionApp/src/numDetailsPackage/NumberDetails.java
  BaseConversionApp/src/numberConvertionPackage/NumberConversion.java
  BaseConversionApp/src/validationPackage/Validation.java
  CPP/lcs.cpp
  CPP/stockSpan.cpp
Labels: hacktoberfest-accepted

#10 Added No of Distinct Islands problem Solution
  Python/No_of_Distinct_Islands.py
Labels: hacktoberfest-accepted

#11 added search dropdown
  searchDropDown/index.html
  searchDropDown/script.tsx
  searchDropDown/styles.scss
Labels: hacktoberfest-accepted

#13 Added tic tac toe game in python
  Python/tic-tac-toe.py
Labels: hacktoberfest-accepted

#12 Added heap sort code in python
  Python/Heap_Sort.py
Labels: hacktoberfest-accepted

#14 added snake-game.py
  Python/Snake-Game.py
Labels: hacktoberfest-accepted

#17 added calculator
  Python/Simple-Calculator.py
Labels: hacktoberfest-accepted

#16 Create Simple_Calculator.py
  Python/Simple_Calculator.py
Labels: hacktoberfest-accepted

#15 Textual error
  index.html
Labels: hacktoberfest-accepted

#19 added login_form in Angular
  Angular/Login_Form/.browserslistrc
  Angular/Login_Form/.editorconfig
  Angular/Login_Form/.gitignore
  Angular/Login_Form/.vscode/extensions.json
  Angular/Login_Form/.vscode/launch.json
  Angular/Login_Form/.vscode/tasks.json
  Angular/Login_Form/README.md
  Angular/Login_Form/angular.json
  Angular/Login_Form/karma.conf.js
  Angular/Login_Form/package-lock.json
  Angular/Login_Form/package.json
  Angular/Login_Form/src/app/app-routing.module.ts
  Angular/Login_Form/src/app/app.component.css
  Angular/Login_Form/src/app/app.component.html
  Angular/Login_Form/src/app/app.component.spec.ts
  Angular/Login_Form/src/app/app.component.ts
  Angular/Login_Form/src/app/app.module.ts
  Angular/Login_Form/src/app/components/footer/footer.component.css
  Angular/Login_Form/src/app/components/footer/footer.component.html
  Angular/Login_Form/src/app/components/footer/footer.component.spec.ts
  Angular/Login_Form/src/app/components/footer/footer.component.ts
  Angular/Login_Form/src/app/components/navbar/navbar.component.css
  Angular/Login_Form/src/app/components/navbar/navbar.component.html
  Angular/Login_Form/src/app/components/navbar/navbar.component.spec.ts
  Angular/Login_Form/src/app/components/navbar/navbar.component.ts
  Angular/Login_Form/src/app/pages/home/home.component.css
  Angular/Login_Form/src/app/pages/home/home.component.html
  Angular/Login_Form/src/app/pages/home/home.component.spec.ts
  Angular/Login_Form/src/app/pages/home/home.component.ts
  Angular/Login_Form/src/app/pages/login/login.component.css
  Angular/Login_Form/src/app/pages/login/login.component.html
  Angular/Login_Form/src/app/pages/login/login.component.spec.ts
  Angular/Login_Form/src/app/pages/login/login.component.ts
  Angular/Login_Form/src/app/pages/signup/signup.component.css
  Angular/Login_Form/src/app/pages/signup/signup.component.html
  Angular/Login_Form/src/app/pages/signup/signup.component.spec.ts
  Angular/Login_Form/src/app/pages/signup/signup.component.ts
  Angular/Login_Form/src/app/services/helper.ts
  Angular/Login_Form/src/app/services/user.service.spec.ts
  Angular/Login_Form/src/app/services/user.service.ts
  Angular/Login_Form/src/assets/.gitkeep
  Angular/Login_Form/src/assets/logo.jpg
  Angular/Login_Form/src/environments/environment.prod.ts
  Angular/Login_Form/src/environments/environment.ts
  Angular/Login_Form/src/favicon.ico
  Angular/Login_Form/src/index.html
  Angular/Login_Form/src/main.ts
  Angular/Login_Form/src/polyfills.ts
  Angular/Login_Form/src/styles.css
  Angular/Login_Form/src/test.ts
  Angular/Login_Form/tsconfig.app.json
  Angular/Login_Form/tsconfig.json
  Angular/Login_Form/tsconfig.spec.json
  Readme.md
Labels: hacktoberfest-accepted

#18 Added Encription of Files
  CPP/encryptingfiles.cpp
Labels: hacktoberfest-accepted
